# Generated by Django 3.0.4 on 2021-09-20 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Diary', max_length=16, verbose_name='日記名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '日記',
            },
        ),
        migrations.CreateModel(
            name='DiaryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日付')),
                ('keyword', models.CharField(max_length=62, verbose_name='キーワード')),
                ('body', models.TextField(verbose_name='本文')),
                ('img_path', models.CharField(max_length=256, verbose_name='画像パス')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gentext.Diary')),
            ],
            options={
                'verbose_name_plural': '日記ページ',
            },
        ),
    ]
