# Generated by Django 3.0.4 on 2021-09-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gentext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypage',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り'),
        ),
        migrations.AlterField(
            model_name='diarypage',
            name='img_path',
            field=models.CharField(default='', max_length=256, verbose_name='画像パス'),
        ),
        migrations.CreateModel(
            name='DiaryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(default='00AFCC', max_length=6, verbose_name='メインカラー')),
                ('sub_color', models.CharField(default='4169E1', max_length=6, verbose_name='サブカラー')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gentext.Diary')),
            ],
        ),
    ]
